### ISSUE TITLE
Add a third parameter to handle selected node

### ISSUE THREAD

**Issue by lijunle** [donum/gulp-xpath#1]
It is weird to always join the node as string ([source](https://github.com/donum/gulp-xpath/blob/master/index.js#L66))

It could be better to provide a third method to convert the node to string. Like this:

``` js
gulp.src(['./news/*.xml'])
    .pipe(xpath("/news-items/news/@attr",{"exsl":"http://exslt.org/common"},function(node){ return node.value; }))
    .pipe(concat('git_news.txt'))
    .pipe(gulp.dest('./news'));
```

**Comment by donum** [comment]
Done!

**Comment by lijunle** [comment]
Hi, @donum . Thanks for working on this.

I am sorry that, I have not clearly understand my requirement. With some hack, I find that, besides control on how **individual node** toString, it could be better to control how the **nodes** toString. It means, for the custom function, a single node is not enough.

From the code aspect, here is my proposal:

``` js
// around line 74
var func = customFunction || defaultFunc;
var output = func(result);
return output;
```

Then, the `defaultFunc` could be:

``` js
function defaultFunc(nodes) {
    return nodes.map(n => n.toString()).join('');
}
```

On the custom function, it can be doing JSON stringify and etc.

---

If you want to be backward compatible (with your current implementation), another options is to provide more parameters to the custom function `(currentNode, currentIndex, fullNodeList)`, just same as the [`Array.prototype.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) method.

BTW, the custom function is actually doing the `map` thing, map from a XML node to a string.

If you think it is OK, I can make a PR. :smile:

**Comment by donum** [comment]
Hi @lijunle,

I think backward compatibility with 1.1.0 is not necessary, because the version is just one day old. I see your requirement.

I don't get the benefit from combining the two functions into one, because the function will be called on each node anyway. What do you do with a full nodelist multiple times?!

Please keep in mind that the separate nodelist function you're describing would be _per file in stream_. Is that really what you want?

Is there a better way to work with the parameters? Could an object as the second parameter that contains _all options_ and all _callbacks_ be an option like it is often the case in the JQuery world?

I am open to PR, but first I would like to discuss this. 

Daniel

**Comment by lijunle** [comment]
OK, let me describe my full scenario.

I have a `csproj` file (Visual Studio project file), it is just a normal XML file. I want to extract some information from it and generate a **JSON** file.

I am happy to get the node list with your great plugin, but then, I need to serialize the node list to a JSON object (JSON array). So, I need to prepend the `{` at first, append `}` at the end, skip `,` or the last element (something like this).

I am not handling full node list multiple times, my hack just get the full time and handle them as a bundle **once**. 

---

If the custom function is passed with the full node list. I can handle them as a bundle:

``` js
function customFunc(nodes) {
    return JSON.stringify(nodes.map(n => n.value)); // this will be ['a', 'b', 'c']
}
```

If the custom function is passed as the `map` function does, I can serialize it to JSON string with a little hack:

``` js
function customFunc(node, index, list) {
    var result = '';
    if (index == 0) result += '['; // hack the first character
    result += JSON.stringify(node.value);
    if (index != list.length - 1) result += ','; else result += ']'; // hack the end character
}
```

I think both are OK. Do you have any idea on it?

**Comment by lijunle** [comment]
@donum Do you have any idea on this?

**Comment by donum** [comment]
Hi,

I am currently traveling for two weeks and will change the script after that. 

Sent from my mobile.

**Comment by lijunle** [comment]
Great! :smile: 

Actually, I have send a PR #2 to resolve this.

**Comment by lijunle** [comment]
@donum  do you have ideas on the PR?

**Comment by lijunle** [comment]
@donum could you please take some time to look this the PR?
